[Add]: TensorRT Support
stefanopini/simple-HigherHRNet pull request #14
Opened 2022-10-23 21:06 UTC by gpastal24

Adding tensorrt support for HigherHRNet

2022-11-06 18:07 UTC, stefanopini requested changes
Hi @gpastal24 , thanks for the great contribution!!

The code looks good to me in general (still have to try running it though).

There are a few minor things to fix before merging:
- there is a lot of commented code that seems old/debug code, it should be removed
- some docstrings of the main functions are missing
- `__pycache__` files shouldn't be committed
- I would put all the utils from yolov5 in a subfolder of utils, e.g. `utils/yolov5`
- I would split the export.py file in two parts:
  - `utils/yolov5/export.py` with all the functions that have remained untouched from the original yolov5 repo
  - `scripts/export_model.py` with the actual functions that have changed to work with SimplerHRNet, e.g. including `main`, `parse_opt`, `run`
- other comments part of the review

I will create a PR to update your PR in the next few days. Then I'll ask your review and if everything looks good, we can merge it into your PR and then yours into the master branch.
Alternatively, please feel free to make changes to your PR directly to address my comments! I can review the changes when they're ready.

2022-11-06 18:07 UTC, stefanopini commented on SimpleHigherHRNet.py
> +                 trt_=False):
I would use a more explicit name, e.g. `enable_tensorrt`.
The variable should also be added to the docstring.

2022-11-06 18:07 UTC, stefanopini commented on SimpleHigherHRNet.py
> +                    device = torch.device('cuda:0')
I think this should be
```suggestion
                raise ValueError('TensorRT does not support cpu device.')
```

2022-11-06 18:07 UTC, stefanopini commented on scripts/live-demo.py
> +    parser.add_argument("--trt_",action='store_true')
Same here, more explicit name and param description.

2022-11-06 18:07 UTC, stefanopini commented on scripts/live-demo.py
> +                        type=str, default="./pose_higher_hrnet_w32_512.pth")
The default weight path should not change

2022-11-06 18:07 UTC, stefanopini commented on misc/utils.py
> +    def __init__(self, engine=None, input_names=None, output_names=None, input_flattener=None, output_flattener=None,path=None,device=None):
Missing docstring for the class/__init__ method

2022-11-06 18:07 UTC, stefanopini commented on export.py
> +        help='torchscript, onnx, openvino, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, paddle')
Are all these params needed? Some of them seem to be relevant to yolov5 only

2022-11-06 21:14 UTC, gpastal24 commented
Hi, thanks for your time. I think most of your comments have been addressed.
If you wish to test this install nvidia-pyindex and tensorrt

` pip3 install nvidia-pyindex nvidia-tensorrt==7.2.3.4`

Trt 7 produces better results for me, but maybe this has to do with different cudnn versions between torch and trt.

` python3 scripts/export_model.py --device 0 --half` 

This should produce the fp16 engine.

` python3 scripts/live-demo.py --enable_tensorrt --filename=<> --hrnet_weights='pose_higher_hrnet_w32_512.engine'`

2022-11-21 00:53 UTC, stefanopini commented
Hi @gpastal24 , I tested your code on Google Colab with CUDA 11/TensorRT 8.5 and it worked smoothly! Thanks a lot for the great contribution! ❤️ 

The code has still some minor style issues so I'm going to merge it into a new branch 'tensorrt', make minor changes to integrate/align it with the rest of the repo and then port the commits into the master branch.
Thanks again, I'll keep you posted on the next steps!

2022-11-21 00:56 UTC, merged